name: crop
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  image_picker: ^1.0.5
  image_cropper: ^5.0.1
  intl: ^0.19.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  activout_firebase_options_selector: ^1.0.0
  firebase_database: ^10.4.0
  font_awesome_flutter: ^10.7.0
  fancy_flutter_dialog: ^1.0.1
  http: ^1.2.0
  firebase_storage: ^11.6.7
  cached_network_image: ^3.3.1
  url_launcher: ^6.2.5
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - imagen/logoApp.png