// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrlf4QOYu63A4oa12ACYBhSBJABaYwjsQ',
    appId: '1:984304074137:web:c0a095668c0d73785ca708',
    messagingSenderId: '984304074137',
    projectId: 'crop-5ff1a',
    authDomain: 'crop-5ff1a.firebaseapp.com',
    storageBucket: 'crop-5ff1a.appspot.com',
    measurementId: 'G-JTKP7NJSL2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmdQJj4pUkF2NMECHvQguS9WGVrpufaMo',
    appId: '1:984304074137:android:c97c7a606d25c0b55ca708',
    messagingSenderId: '984304074137',
    projectId: 'crop-5ff1a',
    storageBucket: 'crop-5ff1a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBB7INvMgb22zo0w-98XVk2qrDG2mJwoKU',
    appId: '1:984304074137:ios:6988f8fe0a7a9b9f5ca708',
    messagingSenderId: '984304074137',
    projectId: 'crop-5ff1a',
    storageBucket: 'crop-5ff1a.appspot.com',
    iosBundleId: 'com.example.crop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBB7INvMgb22zo0w-98XVk2qrDG2mJwoKU',
    appId: '1:984304074137:ios:ce2fc838a20a9aa15ca708',
    messagingSenderId: '984304074137',
    projectId: 'crop-5ff1a',
    storageBucket: 'crop-5ff1a.appspot.com',
    iosBundleId: 'com.example.crop.RunnerTests',
  );
}
